-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 17:19:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assignmentjava4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `assignmentjava4` ;

-- -----------------------------------------------------
-- Schema assignmentjava4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignmentjava4` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `assignmentjava4` ;

-- -----------------------------------------------------
-- Table `assignmentjava4`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignmentjava4`.`users` ;

CREATE TABLE IF NOT EXISTS `assignmentjava4`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `userRole` BIT(1) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignmentjava4`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignmentjava4`.`cart` ;

CREATE TABLE IF NOT EXISTS `assignmentjava4`.`cart` (
  `idCart` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCart`),
  INDEX `fk_cart_users` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_cart_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `assignmentjava4`.`users` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignmentjava4`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignmentjava4`.`category` ;

CREATE TABLE IF NOT EXISTS `assignmentjava4`.`category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignmentjava4`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignmentjava4`.`product` ;

CREATE TABLE IF NOT EXISTS `assignmentjava4`.`product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `image` VARCHAR(50) NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_product_category` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `assignmentjava4`.`category` (`idCategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignmentjava4`.`cart_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignmentjava4`.`cart_detail` ;

CREATE TABLE IF NOT EXISTS `assignmentjava4`.`cart_detail` (
  `idCart` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idCart`, `idProduct`),
  INDEX `fk_cart_detail_product` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_cart_detail_cart`
    FOREIGN KEY (`idCart`)
    REFERENCES `assignmentjava4`.`cart` (`idCart`),
  CONSTRAINT `fk_cart_detail_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `assignmentjava4`.`product` (`idProduct`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
